inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength: 
  Max: 20
Metrics/BlockLength:
  Max: 130
Layout/LineLength:
  Max: 160
  
